---
# NOTE(mattymo): This can be removed after release of Calico 2.1

- name: Get timestamp from oldest dhclient pid
  shell: "stat -t /proc/$(pgrep -o dhclient) | cut -d' ' -f14"
  register: oldest_dhclient_time

- name: check if /etc/dhclient.conf exists
  stat:
    path: /etc/dhclient.conf
  register: dhclient_find_stat

- name: target dhclient conf file for /etc/dhclient.conf
  set_fact:
    dhclientconffile: /etc/dhclient.conf
  when: dhclient_find_stat.stat.exists

- name: target dhclient conf file for /etc/dhcp/dhclient.conf
  set_fact:
    dhclientconffile: /etc/dhcp/dhclient.conf
  when: not dhclient_find_stat.stat.exists

- name: Gather info on dhclient.conf
  stat:
    path: "{{ dhclientconffile }}"
  register: dhclient_stat

- name: See if oldest dhclient process is older than dhclient.conf
  set_fact:
    needs_network_reset: "{{ oldest_dhclient_time.stdout != '' and oldest_dhclient_time.stdout|int < dhclient_stat.stat.mtime }}"

- name: Set networking service name
  set_fact:
    networking_service_name: >-
      {% if ansible_os_family == "RedHat" -%}
      network
      {%- elif ansible_os_family == "Debian" -%}
      networking
      {%- endif %}

- name: Restart networking, kubelet, and docker services
  shell: "{{ item }}"
  when: needs_network_reset|bool
  with_items:
  - pkill -9 dhclient
  - systemctl restart {{ networking_service_name }}
  - systemctl restart kubelet
  - systemctl restart docker 
