---
- hosts: k8s-cluster
  roles:
    - { role: postinstall, tags: postinstall }
    - { role: netcheck/dns, tags: netcheck }
    - { role: netcheck/ipip, tags: netcheck }

- hosts: kube-master
  roles:
    - { role: netcheck, tags: netcheck }
