---
- hosts: all
  serial: 100
  gather_facts: no
  roles:
    - { role: preinstall, tags: preinstall }

- hosts: localhost
  become: true
  gather_facts: no
  roles:
    - { role: configure_logs, tags: configure_logs }
