handler: ansible_local
version: 1.0.0
input:
    ip:
      schema: str!
      value:
    name:
      schema: str
      value: a node
    location_id:
      schema: str!
      value: $uuid
      reverse: True

tags: [resources=node]
