---
- name: pick dnsmasq cluster IP
  set_fact:
    dnsmasq_server: >-
      {%- if skip_dnsmasq|bool -%}{{ skydns_server }}{%- else -%}{{ dns_server }}{%- endif -%}

- name: Wait for kubedns to be ready
  shell: "nslookup kubernetes.default.svc.{{ dns_domain }} {{ dnsmasq_server }}"
  register: kubernetes_resolvable
  until: kubernetes_resolvable.rc == 0
  delay: 5
  retries: 5
  changed_when: false

- name: Copy network test script
  copy:
    src: test_networking.sh
    dest: "{{ bin_dir }}/test_networking.sh"
    owner: root
    group: root
    mode: 0755
  become: true

- name: Test networking connectivity
  shell: "bash {{ bin_dir }}/test_networking.sh"
  environment:
    KUBEDNS_IP: "{{ skydns_server }}"
    DNSMASQ_IP: "{{ dnsmasq_server }}"
    ADMIN_USER: "{{ ansible_user }}"
    ADMIN_IP: "{{ hostvars[groups['kube-master'][0]]['ip'] | default(hostvars[groups['kube-master'][0]]['ansible_default_ipv4']['address']) }}"
    SLAVE_IPS: "{{ ip }}"
  changed_when: false
  become: false
