log_path: /var/log/ansible/
conf_file: /etc/ansible/ansible.cfg
callback_plugins:
  - name: human_readable_plugin
    enabled: true
    repo: https://gist.github.com/cd706de198c85a8255f6.git
    rev: cd706de198c85a8255f6
    script_path: ./
    script_name: human_log.py
# TODO(bogdando) fix for ansible 2.0 or find another plugin
#  - name: timestamp_plugin
#    enabled: false
#    repo: https://github.com/ginsys/ansible-plugins.git
#    rev: 05fe432c8c20f7a548c290bb24a6108b75bb4449
#    script_path: ./callback_plugins
#    script_name: timestamp.py
callback_plugin_path: /usr/share/ansible/plugins/callback
# Define custom diag info to collect
debug: false
commands:
  - name: git_info
    cmd: cat {workspace/kargo,kargo}/.git/logs/HEAD
  - name: timedate_info
    cmd: timedatectl status
  - name: boots_info
    cmd: journalctl --list-boots --utc --no-pager
  - name: space_info
    cmd: df -h
  - name: kernel_info
    cmd: uname -r
  - name: distro_info
    cmd: cat /etc/issue.net
  - name: docker_info
    cmd: docker info
  - name: ip_info
    cmd: ip -4 -o a
  - name: route_info
    cmd: ip ro
  - name: proc_info
    cmd: ps auxf | grep -v ]$
  - name: systemctl_info
    cmd: systemctl status
  - name: k8s_resolve_info
    cmd: host kubernetes
  - name: k8s_info
    cmd: kubectl get all --all-namespaces -o wide
  - name: k8s_dump_info
    cmd: kubectl get all --all-namespaces -o yaml
  - name: errors_info
    cmd: journalctl -p err --utc --no-pager
logs:
  - /var/log/ansible/ansible.log
  - /var/log/syslog
  - /var/log/daemon.log
  - /var/log/kern.log
  - /etc/resolv.conf
  - kargo/cluster.yml
  - kargo/kargo_default_ubuntu.yaml
  - kargo/kargo_default_debian.yaml
  - kargo/kargo_default_common.yaml
  - kargo/inventory/inventory.cfg
  - workspace/kargo/cluster.yml
  - workspace/kargo/kargo_default_ubuntu.yaml
  - workspace/kargo/kargo_default_debian.yaml
  - workspace/kargo/kargo_default_common.yaml
  - workspace/kargo/inventory/inventory.cfg
