bin_dir: /usr/local/bin
log_path: /var/log/ansible/
conf_file: /etc/ansible/ansible.cfg
# Define custom diag info to collect
commands:
  - name: git_info
    cmd: find . -type d -name .git -execdir sh -c 'gen-gitinfos.sh global|head -12' \;
  - name: timedate_info
    cmd: timedatectl status
  - name: boots_info
    cmd: journalctl --list-boots --utc --no-pager
  - name: space_info
    cmd: df -h
  - name: kernel_info
    cmd: uname -r
  - name: distro_info
    cmd: cat /etc/issue.net
  - name: docker_info
    cmd: docker info
  - name: ip_info
    cmd: ip -4 -o a
  - name: route_info
    cmd: ip ro
  - name: proc_info
    cmd: ps auxf | grep -v ]$
  - name: systemctl_info
    cmd: systemctl status
  - name: systemctl_failed_info
    cmd: systemctl --state=failed --no-pager
  - name: k8s_resolve_info
    cmd: host kubernetes
  - name: k8s_info
    cmd: kubectl get all --all-namespaces -o wide
  - name: k8s_dump_info
    cmd: kubectl get all --all-namespaces -o yaml
  - name: errors_info
    cmd: journalctl -p err --utc --no-pager
  - name: etcd_info
    cmd: etcdctl --debug cluster-health
  - name: calico_info
    cmd: calicoctl status
  - name: sysctl_info
    cmd: sysctl -a
logs:
  - /var/log/ansible/ansible.log
  - /var/log/syslog
  - /var/log/daemon.log
  - /var/log/kern.log
  - /etc/resolv.conf
  - "{{searchpath}}/kargo/cluster.yml"
  - "{{searchpath}}/kargo/inventory/group_vars/all.yml"
  - "{{searchpath}}/inventory/inventory.cfg"
  - "{{searchpath}}/inventory/kargo_default_ubuntu.yaml"
  - "{{searchpath}}/inventory/kargo_default_debian.yaml"
  - "{{searchpath}}/inventory/kargo_default_common.yaml"
